spring:
  flyway:
    enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/social_network
    username: postgres
    password: root
  jpa:
    show-sql: true
    properties.hibernate:
      default_schema: public
      dialect: org.hibernate.dialect.PostgreSQL91Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    database: postgresql
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration

security:
  basic:
    enable: false

  jwt:
    uri: /auth/**
    header: Authorization
    prefix: Bearer
    expiration: 86400
    secret: JwtSecretKey

server:
  error:
    whitelabel:
      enabled: false
  port: 8081


#app
app:
  system-user-email: outwork@gmail.com
  auth:
    not-auth-endpoints: /login,
                        /registration